#!/usr/bin/env bash
# Writes docs/screens.md from the screen snapshot references — one section per screen, every variant.
set -euo pipefail
cd "$(dirname "$0")/.."

snapshots="Tests/SnapshotTests/Screens/__Snapshots__"
out="docs/screens.md"
mkdir -p docs

{
  echo "# UI Screenshots"
  echo
  echo "Generated from the screen snapshot references — do not edit by hand. Regenerate with:"
  echo
  echo '```bash'
  echo "make record-snapshots && scripts/generate-screens-readme.sh"
  echo '```'
  for suite in "$snapshots"/*ScreenViewSnapshotTests; do
    [ -d "$suite" ] || continue
    name="$(basename "$suite")"
    screen="${name%ScreenViewSnapshotTests}"
    echo
    echo "## $screen"
    echo
    line=""
    for png in "$suite"/*.png; do
      [ -f "$png" ] || continue
      variant="$(basename "$png" .png)"
      line+="<img src=\"../$png\" width=\"200\" alt=\"$screen — $variant\" /> "
    done
    echo "${line% }"
  done
  echo
  echo "---"
  echo
  echo "_Generated by \`scripts/generate-screens-readme.sh\`_"
} > "$out"

echo "wrote $out" >&2
